# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-04-10 09:52
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='alumni_model',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(default='', max_length=200, verbose_name='Nama Lengkap')),
                ('nim', models.CharField(default='', max_length=10, verbose_name='NIM')),
                ('konsentrasi', models.CharField(default='', max_length=30, verbose_name='Konsentrasi')),
                ('tempat_kerja', models.CharField(default='', max_length=100, verbose_name='Nama Perusahaan')),
                ('jabatan', models.CharField(default='', max_length=100, verbose_name='Posisi Pekerjaan')),
                ('tahun_masuk', models.PositiveIntegerField(default='', validators=[django.core.validators.MaxValueValidator(9999)], verbose_name='Tahun Masuk')),
                ('tahun_keluar', models.PositiveIntegerField(default='', validators=[django.core.validators.MaxValueValidator(9999)], verbose_name='Tahun Keluar')),
            ],
        ),
    ]
