# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-04-08 04:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='berita_model',
            name='user',
        ),
        migrations.DeleteModel(
            name='berita_model',
        ),
    ]
