# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-04-10 09:52
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import stdimage.models
import stdimage.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='berita_model',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('judul', models.CharField(default='', max_length=200)),
                ('slug', models.SlugField(unique=True)),
                ('image', stdimage.models.StdImageField(blank=True, upload_to='upload/berita', validators=[stdimage.validators.MaxSizeValidator(1028, 768)])),
                ('content', models.TextField()),
                ('draft', models.BooleanField(default=False)),
                ('publish', models.DateField()),
                ('updated', models.DateTimeField(auto_now=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('tag', models.CharField(default='', max_length=20)),
                ('user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated'],
            },
        ),
        migrations.CreateModel(
            name='gallery_model',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('judul', models.CharField(default='', max_length=20, verbose_name='Judul Foto')),
                ('caption', models.CharField(default='', max_length=300, verbose_name='Caption Foto')),
                ('image', stdimage.models.StdImageField(upload_to='upload/gallery', validators=[stdimage.validators.MaxSizeValidator(1028, 768)], verbose_name='Foto')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='staff_model',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(default='', max_length=20, verbose_name='Nama Lengkap')),
                ('nama_display', models.CharField(default='', max_length=14, verbose_name='Nama yang Ditampilkan')),
                ('nidn', models.CharField(default='', max_length=10, verbose_name='NIDN')),
                ('jabatan', models.CharField(default='', max_length=30, verbose_name='Jabatan Akademik')),
                ('gelar', models.CharField(default='', max_length=30, verbose_name='Gelar Pendidikan')),
                ('pendidikan1', models.CharField(default='', max_length=30, verbose_name='Universitas Jenjang SI')),
                ('pendidikan2', models.CharField(blank=True, default='', max_length=30, verbose_name='Universitas Jenjang S2')),
                ('pendidikan3', models.CharField(blank=True, default='', max_length=30, verbose_name='Universitas Jenjang S3')),
                ('bidang_keahlian1', models.CharField(default='', max_length=50, verbose_name='Bidang Keahlian S1')),
                ('bidang_keahlian2', models.CharField(blank=True, default='', max_length=50, verbose_name='Bidang Keahlian S2')),
                ('bidang_keahlian3', models.CharField(blank=True, default='', max_length=50, verbose_name='Bidang Keahlian S3')),
                ('biografi', models.TextField(blank=True, default='', verbose_name='Biografi')),
                ('foto', stdimage.models.StdImageField(upload_to='upload/dosen', validators=[stdimage.validators.MaxSizeValidator(1028, 768)])),
            ],
        ),
    ]
