# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-04-10 09:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staff_model',
            name='gelar',
        ),
        migrations.AddField(
            model_name='staff_model',
            name='gelar1',
            field=models.CharField(default='', max_length=30, verbose_name='Gelar Pendidikan S1'),
        ),
        migrations.AddField(
            model_name='staff_model',
            name='gelar2',
            field=models.CharField(default='', max_length=30, verbose_name='Gelar Pendidikan S2'),
        ),
        migrations.AddField(
            model_name='staff_model',
            name='gelar3',
            field=models.CharField(default='', max_length=30, verbose_name='Gelar Pendidikan S3'),
        ),
    ]
