# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-04-10 02:16
from __future__ import unicode_literals

from django.db import migrations
import stdimage.models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff_model',
            name='foto',
            field=stdimage.models.StdImageField(upload_to='upload/dosen'),
        ),
    ]
