# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-04-10 12:11
from __future__ import unicode_literals

from django.db import migrations
import stdimage.models
import stdimage.validators


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_auto_20170410_1208'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gallery_model',
            name='image',
            field=stdimage.models.StdImageField(blank=True, upload_to='upload/gallery', validators=[stdimage.validators.MaxSizeValidator(1028, 768)], verbose_name='Foto'),
        ),
    ]
