# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-04-10 16:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_auto_20170410_1211'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff_model',
            name='penelitian',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Penelitian Google Scholar'),
        ),
    ]
