# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-04-11 07:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_staff_model_penelitian'),
    ]

    operations = [
        migrations.AddField(
            model_name='kurikulum_model',
            name='wajib',
            field=models.BooleanField(default='False'),
        ),
    ]
