# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-04-11 11:12
from __future__ import unicode_literals

from django.db import migrations, models
import stdimage.models
import stdimage.validators


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_kurikulum_model_wajib'),
    ]

    operations = [
        migrations.CreateModel(
            name='beranda_model',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('judul_besar', models.CharField(default='', max_length=100, verbose_name='Judul Tagline')),
                ('keterangan_singkat', models.CharField(default='', max_length=200, verbose_name='Keterangan Singkat')),
                ('nama_button', models.CharField(default='', max_length=20, verbose_name='Nama Button')),
                ('link_button', models.CharField(default='', max_length=400, verbose_name='Link Button')),
                ('foto', stdimage.models.StdImageField(blank=True, upload_to='upload/beranda', validators=[stdimage.validators.MaxSizeValidator(4300, 2850)], verbose_name='Foto (Maks : 4300x2850)')),
                ('tampil', models.BooleanField(default=False, verbose_name='Ditampilkan')),
            ],
        ),
        migrations.AlterField(
            model_name='kurikulum_model',
            name='wajib',
            field=models.BooleanField(default='False', verbose_name='Mata Kuliah Wajib/Pilihan (*Jika Wajib Dicentang)'),
        ),
    ]
