# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-04-11 14:16
from __future__ import unicode_literals

from django.db import migrations, models
import stdimage.models
import stdimage.validators


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_auto_20170411_1112'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beranda_model',
            name='foto',
            field=stdimage.models.StdImageField(blank=True, upload_to='upload/beranda', validators=[stdimage.validators.MaxSizeValidator(4300, 2850)], verbose_name='Foto(Maks : 4300px X 2850px)'),
        ),
        migrations.AlterField(
            model_name='beranda_model',
            name='nama_button',
            field=models.CharField(default='', max_length=50, verbose_name='Nama Button'),
        ),
    ]
