# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-04-13 16:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0008_auto_20170411_1416'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff_model',
            name='bidang_keahlian1',
            field=models.CharField(default='', max_length=80, verbose_name='Bidang Keahlian S1'),
        ),
        migrations.AlterField(
            model_name='staff_model',
            name='bidang_keahlian2',
            field=models.CharField(blank=True, default='', max_length=80, verbose_name='Bidang Keahlian S2'),
        ),
        migrations.AlterField(
            model_name='staff_model',
            name='bidang_keahlian3',
            field=models.CharField(blank=True, default='', max_length=80, verbose_name='Bidang Keahlian S3'),
        ),
        migrations.AlterField(
            model_name='staff_model',
            name='pendidikan1',
            field=models.CharField(default='', max_length=100, verbose_name='Universitas Jenjang SI'),
        ),
        migrations.AlterField(
            model_name='staff_model',
            name='pendidikan2',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Universitas Jenjang S2'),
        ),
        migrations.AlterField(
            model_name='staff_model',
            name='pendidikan3',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Universitas Jenjang S3'),
        ),
        migrations.AlterField(
            model_name='staff_model',
            name='penelitian',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='Penelitian Google Scholar'),
        ),
    ]
