# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-04-15 01:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0010_auto_20170413_1756'),
    ]

    operations = [
        migrations.CreateModel(
            name='document_model',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deskripsi', models.CharField(default='', max_length=100)),
                ('file', models.FileField(upload_to='upload/document')),
                ('keterangan', models.CharField(default='', max_length=50)),
                ('tanggal', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name='beranda_model',
        ),
    ]
