# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-04-15 04:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0011_auto_20170415_0122'),
    ]

    operations = [
        migrations.CreateModel(
            name='dokumen_model',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deskripsi', models.CharField(default='', max_length=100, verbose_name='Deskripsi')),
                ('file', models.FileField(upload_to='upload/document', verbose_name='File')),
                ('keterangan', models.CharField(default='', max_length=50, verbose_name='Keterangan')),
                ('tanggal', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name='document_model',
        ),
    ]
