# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-04-15 05:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0013_auto_20170415_0502'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dokumen_model',
            name='deskripsi',
            field=models.CharField(default='', max_length=30, verbose_name='Nama Dokumen'),
        ),
        migrations.AlterField(
            model_name='dokumen_model',
            name='keterangan',
            field=models.TextField(default='', max_length=300, verbose_name='Deskripsi'),
        ),
    ]
