# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-04-15 05:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0014_auto_20170415_0525'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dokumen_model',
            name='keterangan',
            field=models.TextField(verbose_name='Deskripsi'),
        ),
    ]
