# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-16 14:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0015_auto_20170415_0530'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff_model',
            name='posisi',
            field=models.CharField(default='', max_length=30),
        ),
    ]
