# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-16 14:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0016_staff_model_posisi'),
    ]

    operations = [
        migrations.CreateModel(
            name='ukm_model',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_ukm', models.CharField(default='', max_length=30, verbose_name='Nama UKM')),
                ('link', models.CharField(default='', max_length=30, verbose_name='Link')),
            ],
        ),
    ]
