# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-16 16:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0017_ukm_model'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ukm_model',
            name='link',
        ),
        migrations.RemoveField(
            model_name='ukm_model',
            name='nama_ukm',
        ),
        migrations.AddField(
            model_name='ukm_model',
            name='link_himatif',
            field=models.CharField(default='', max_length=30, verbose_name='Link HIMATIF'),
        ),
        migrations.AddField(
            model_name='ukm_model',
            name='nama_fosti',
            field=models.CharField(default='', max_length=30, verbose_name='Link FOSTI'),
        ),
    ]
