# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-16 16:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0018_auto_20170416_1617'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ukm_model',
            old_name='nama_fosti',
            new_name='link_fosti',
        ),
    ]
