# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-16 16:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0019_auto_20170416_1618'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ukm_model',
            name='link_fosti',
            field=models.CharField(default='', max_length=300, verbose_name='Link FOSTI'),
        ),
        migrations.AlterField(
            model_name='ukm_model',
            name='link_himatif',
            field=models.CharField(default='', max_length=300, verbose_name='Link HIMATIF'),
        ),
    ]
