# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-19 15:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0020_auto_20170416_1639'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kurikulum_model',
            name='kode',
            field=models.CharField(default='', max_length=10, verbose_name='Kode MK'),
        ),
    ]
