# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-08-04 01:36
from __future__ import unicode_literals

from django.db import migrations
import stdimage.models
import stdimage.validators


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0021_auto_20170419_1517'),
    ]

    operations = [
        migrations.AlterField(
            model_name='berita_model',
            name='image',
            field=stdimage.models.StdImageField(blank=True, upload_to='upload/berita', validators=[stdimage.validators.MaxSizeValidator(1300, 1300)]),
        ),
    ]
